### ISSUE TITLE
Failing to install using cpanm

### ISSUE THREAD

**Issue by GeJ** [key-amb/perl5-App-Koyomi#1]
Hello,

I just tried to install App::Koyomi via cpanm and it complained that I had missing dependencies. Although they seem to be properly set in cpanfile, it looks like your META.json doesn't have anything listed in prereqs/runtime.

I'm not familiar with ShipIt, but could it be that there was something missing in the release process? If you would like, I could write a patch for META.json, but I fear that the file might be automatically generated and my changes won't stick.

While young, this module looks very interesting : simple, lightweight, readable and easily understandable. Just what I'm usually looking for.

あざっす!

**Comment by key-amb** [comment]
Thank you for your early try and feedback.
I think I've fixed it in v0.1.2.
Please make a try.

Thank you!

**Comment by key-amb** [comment]
Still missed test modules.
I fixed it in _v0.1.3_.
Hope this work well.

**Comment by key-amb** [comment]
... It's a shame I still missed `script/koyomi` to dist package.
I hope you can get complete set from _v0.1.4_.

**Comment by GeJ** [comment]
LGTM!

I Installed App::Koyomi from a vanilla Perl install and it pulled all the required dependencies and installed the koyomi script.

Thank you very much for taking care of this.

**Comment by key-amb** [comment]
Not at all!
I'm afraid _Koyomi_ is so premature now and probably you'll find some difficulty to use this.

I will improve _Koyomi_ day by day (maybe week by week), but any feedback is welcome!
